Correct TypeError bug
  File "/GIT/L8/l8-python/l8/l8.py", line 31, in docrc
    b = struct.unpack("B", i)[0]
TypeError: a bytes-like object is required, not 'int'